Login_Manager_System
CSC207-2022F-UofT/course-project-choose pull request #26
Opened 2022-11-21 17:22 UTC by ShuHaoLin2002

First edition

2022-11-22 03:17 UTC, hzhqwq reviewed
This commit added docstrings and implemented the login UI well, while the homepage UI still needs to improve.

2022-11-22 04:04 UTC, RitatataVan reviewed
1. Codes adhere to Clean Architecture and SOLID principles, but you omit to push the LoginRequestModel and LoginResponseModel in your branch. 
2. Testing should be included later to present the evidence of code coverage and relevant documentation.
3. HomePageUI can be improved by setting setBounds, setFont, setHorizontalAlignment, etc. if you want.

2022-11-24 01:51 UTC, cyltaracai requested changes
Hi Selina, great work. 
No clean architecture violations is found. However, the pull request is missing a few necessary files to make the clean architecture complete such as presenter, and output boundary. I know your have those files locally but I dont see them on this pull request.

2022-11-24 01:51 UTC, cyltaracai commented on src/main/java/data_access_storage/UserRepo.java
> -        String record_password = accounts.get(email).toString();
please remove this line of code

2022-11-24 01:51 UTC, cyltaracai commented on src/main/java/login_management_system/LoginInteractor.java
> +            return loginOutputBoundary.prepareFailView("Password doesn't match username.");
The error message could be changed to "You have entered an invalid password."

2022-11-24 01:51 UTC, cyltaracai commented on src/main/java/login_management_system/LoginInteractor.java
> +            return loginOutputBoundary.prepareFailView("User doesn't exists.");
The error message could be changed to "You have entered an invalid username."

2022-12-02 04:15 UTC, hzhqwq approved these changes

2022-12-02 14:20 UTC, cyltaracai approved these changes

2022-12-02 23:31 UTC, RitatataVan approved these changes
Great Work

2022-12-03 01:41 UTC, merged